package cc.broomwagon.dao;

import static com.google.common.collect.Maps.newHashMap;
import static java.util.stream.IntStream.range;

import cc.broomwagon.model.Product;
import org.springframework.stereotype.Repository;

import java.util.Map;

/**
 * Dummy dao - returns hardcoded products.
 */
@Repository
public class DummyProductDao implements ProductDao {
    Map<String, Product> products;
    String urlPrefix = "url";

    public DummyProductDao() {
        this.products = newHashMap();
        generateProducts(5, products);
    }

    @Override
    public Iterable<Product> getProducts() {
        return products.values();
    }

    @Override
    public Product getProductByUrl(String url) {
        return products.get(url);
    }

    @Override
    public Product add(Product product) {
        products.put(product.getUrl(), product);
        return product;
    }

    private Map<String, Product> generateProducts(int numberOrProducts, Map<String, Product> products) {
        range(0, numberOrProducts)
                .forEach(index -> {
                    products.put(urlPrefix + index, Product.builder()
                            .title("autogenerated product #" + index)
                            .url(urlPrefix + index)
                            .build());
                });

        return products;
    }
}
