package cc.broomwagon.dao;

import static com.google.common.collect.Maps.newHashMap;

import cc.broomwagon.model.Product;
import org.springframework.stereotype.Repository;

import java.util.Map;

/**
 * Dummy dao - returns hardcoded products.
 */
@Repository
public class DummyProductDao implements ProductDao {
    Map<String, Product> products;
    String urlPrefix = "url";

    public DummyProductDao() {
        this.products = newHashMap();
        generateProducts(5, products);
    }

    @Override
    public Iterable<Product> getProducts() {
        return products.values();
    }

    @Override
    public Product getProductByUrl(String url) {
        return products.get(url);
    }

    private Map<String, Product> generateProducts(int numberOrProducts, Map<String, Product> products) {
        for (int i = 0; i < numberOrProducts; i++) {
            products.put(urlPrefix + i, Product.builder()
                    .title("autogenerated product #" + i)
                    .url(urlPrefix + i)
                    .build());
        }
        return products;
    }
}
