package cc.broomwagon.dao;

import static com.google.common.collect.Maps.newHashMap;
import static java.util.Optional.of;
import static java.util.Optional.ofNullable;
import static java.util.stream.IntStream.range;

import cc.broomwagon.model.Product;
import org.springframework.stereotype.Repository;

import java.util.Collection;
import java.util.Map;
import java.util.Optional;

/**
 * Dummy dao - returns hardcoded products.
 */
@Repository
public class DummyProductDao implements ProductDao {
    Map<String, Product> products;
    String urlPrefix = "url";

    public DummyProductDao() {
        this.products = newHashMap();
        generateProducts(5, products);
    }

    @Override
    public Collection<Product> getProducts() {
        return products.values();
    }

    @Override
    public Optional<Product> getProductByUrl(String url) {
        return ofNullable(products.get(url));
    }

    @Override
    public Optional<Product> getProductById(Long id) {
        return products.values()
                .stream()
                .filter(product -> product.getId().equals(id))
                .findFirst();
    }

    @Override
    public Optional<Product> add(Product product) {
        products.put(product.getUrl(), product);
        return of(product);
    }

    private Map<String, Product> generateProducts(int numberOrProducts, Map<String, Product> products) {
        range(0, numberOrProducts)
                .forEach(index -> {
                    products.put(urlPrefix + index, Product.builder()
                            .id((long) index)
                            .title("autogenerated product #" + index)
                            .url(urlPrefix + index)
                            .build());
                });

        return products;
    }
}
